---
- name: provision configuration files
  sudo:                 yes
  sudo_user:            '{{ seafile_user }}'
  template:
    src:                '{{ item.src }}'
    dest:               '{{ item.dest }}'
    owner:              '{{ seafile_user }}'
    group:              '{{ seafile_user }}'
    mode:               0640
  with_items:
    - src:      'ccnet/ccnet.conf'
      dest:     '{{ seafile_ccnet_dir }}/'
    - src:      'seafile-data/seafile.conf'
      dest:     '{{ seafile_data_dir }}/'
    - src:      'ccnet/seafile.ini'
      dest:     '{{ seafile_ccnet_dir }}/'
    - src:      'conf/seafdav.conf'
      dest:     '{{ seafile_conf_dir }}/'
    - src:      '{{ SEAFILE_SEAHUB_SETTINGS_F }}'
      dest:     '{{ SEAFILE_SEAHUB_SETTINGS }}'
  notify:              restart_seafile

- name:       move the default avatars directory out of the way
  sudo:       yes
  sudo_user:  '{{ seafile_user }}'
  shell:      >
              ORI='{{ seafile_latest_dir }}/seahub/media/avatars';
              test -e $ORI && (test -L $ORI || mv -v $ORI ${ORI}.ori)
  register:     _shell
  changed_when: _shell.stdout_lines|length > 0

- name:       link media folders with local custom data
  sudo:       yes
  sudo_user:  '{{ seafile_user }}'
  file:
    src:      '{{ seafile_seahubdata_dir +"/"+ item }}'
    dest:     '{{ seafile_latest_dir +"/seahub/media/" + item }}'
    owner:    '{{ seafile_user }}'
    group:    '{{ seafile_user }}'
    mode:     0755
    state:    link
    force:    yes
  with_items:
  - avatars
  - custom

- name:       copy default avatars to custom data dir
  sudo:       yes
  sudo_user:  '{{ seafile_user }}'
  shell:      |
              ORI='{{ seafile_latest_dir }}/seahub/media/avatars';
              rsync -ai ${ORI}.ori/ $ORI/
  register:     _shell
  changed_when: _shell.stdout_lines|length > 0

